# le nom de ma pipeline
name: Pipeline 1

# le trigger
on: 
    push:
        branches: [main]
# ce que le pipeline va réaliser
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1
              run: echo "Hello world"
    job2: 
        runs-on: windows-latest

        # oblige le job en cours à attendre le job entre crochet avant de s'éxécuter
        needs: [job1]
        steps:
            - name: My awesome step
              run: mkdir app

            - name:  My other awesome step
              run: dir 
